# Jekyll configuration for Open SDG platform

# Replace the baseurl with the name of this repository. For example, if the repository is named
# "my-site-repository", then update the baseurl like so:
# baseurl: "/my-site-repository"
baseurl: "/cif-cic_dev"
# The next line should be the URL of your data repository published site. To find this,
# go to your data repository in Github, and click "Settings", then scroll down to the
# "Github Pages" section. Copy/paste the link in the green section.
remote_data_prefix: "https://sdg-data-canada-odd-donnees.github.io/cif-data-donnees-cic"
# In the next few items, replace "open-sdg" with the name of your GitHub
# organization, and "open-sdg-data-starter" with the name of your data repository.
# URL for the "Edit Data" button on indicators.
#data_edit_url: http://prose.io/#sdg-data-canada-odd-donnees/cif-data-donnees-cic/edit/develop/data/indicator_[id].csv
# URL for the "Edit Metadata" button on indicators.
#metadata_edit_url: http://prose.io/#sdg-data-canada-odd-donnees/cif-data-donnees-cic/edit/develop/meta/[id].md
#
# The list of languages that are translated. The first one is the default.
languages:
  - en
  - fr


# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: open-sdg/open-sdg@2.4.0-dev

# Replace this title as needed.
title: Canada Indicators For The Sustainable Development Goals
url: ""
data_dir: data
environment: staging

# Automatically create indicator pages, goal pages,
# and some other required pages.
create_indicators:
  layout: indicator
  previous_next_links: true

create_goals:
  layout: goal-by-target
  previous_next_links: true
create_pages:
  - folder: /
    layout: frontpage-alt
  - folder: /goals
    layout: goals
  - folder: /reporting-status
    layout: reportingstatus
  - filename: indicators.json
    folder: /
    layout: indicator-json
  - folder: /search
    layout: search
ignored_disaggregations:
  - Progress

analytics:
  ga_prod: 'G-F9C9LT784Y'

# Sticky share buttons (facebook, twitter and email)
#sharethis_property: '5d279253faeee40012f195e1'

# Replace the email addresses below.
email_contacts:
  questions: statcan.sdg-odd.statcan@statcan.gc.ca
  suggestions: statcan.sdg-odd.statcan@statcan.gc.ca
  functional: statcan.sdg-odd.statcan@statcan.gc.ca

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: Statistics Canada
  adjective: Canadian

# Optionally set a title/body for the frontpage banner. The defaults below point to a standard
# translation, but feel free to change it as needed.
frontpage_introduction_banner:
  title: frontpage.intro_title
  description: frontpage.intro_body

frontpage_goals_grid:
  title: frontpage.heading
  description: frontpage.instructions

frontpage_cards:
  - 
    title: frontpage.download_all
    include: components/download-all-data.html
    
  - 
    title: frontpage.second_header
    content: frontpage.second_content
#    button_label: custom.access
#    button_link: custom.gif_link
    
  - 
    title: frontpage.third_header
    content: frontpage.third_content
      
#    button_label: custom.access
#    button_link: custom.about_link


# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /goals
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: general.goals
 # - path: /reporting-status
 #   translation_key: menu.reporting_status
  - path: /about
    translation_key: menu.about
 # - path: /analysis
 #   translation_key: menu.guidance
 # - path: /related-products
 #   translation_key: menu.related-products
  - path: /faq
    translation_key: menu.faq
  - translation_key: menu.more_info
    dropdown:
      - path: /related-products
        translation_key: menu.related-products
      - path: /methodology
        translation_key: menu.methodology

footer_menu:
  - path: mailto:statcan.sdg-odd.statcan@statcan.gc.ca
    translation_key: menu.contact_us
  - path: https://www.facebook.com/StatisticsCanada/
    translation_key: general.facebook
  - path: https://instagram.com/statcan_eng/
    translation_key: general.instagram
  - path: https://ca.linkedin.com/company/statcan
    translation_key: general.linkedin
  - path: https://www.reddit.com/user/StatCanada/
    translation_key: general.reddit
  - path: https://twitter.com/statcan_eng
    translation_key: general.twitter
  - path: https://www.youtube.com/statisticscanada
    translation_key: general.youtube
  - path: https://www.statcan.gc.ca/
    translation_key: general.statcan
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies

# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
non_global_metadata: indicator.national_metadata

# Hide empty metadata fields.
hide_empty_metadata: true

#Comma separator
decimal_separator: '.'

# Set a base for all goal image URLs. Note that the full goal image path will be
# the base below, completed with: /[language]/[number].png (eg, /fr/6.png).
goal_image_base: https://sdg-data-canada-odd-donnees.github.io/cif-cic_dev/assets/img/cards/inverted

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

# Exclude some files/folders.
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE

# Optionally uncomment and update the settings below to control the mapping functionality.
# These are only a few of the possible settings. For more details, see:
# https://open-sdg.readthedocs.io/en/latest/maps/
map_options:
  minZoom: 2
  maxZoom: 6
  tileURL: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
  tileOptions:
 # attribution: 'My map attribution'
  colorRange: chroma.brewer.BuGn
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#deebf7'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#3182bd'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: '5,5'
map_layers:
  - min_zoom: 2
    max_zoom: 6
    subfolder: regions
    label: Regions

# Recommend accessibility improvements.
accessible_tabs: true
accessible_charts: true

# Specify any custom javascript files.
custom_js:
  - /assets/js/custom.js

# Specify the format of the language toggles. Choices are:
# "dropdown", "links", or "none"
header_language_toggle: dropdown
footer_language_toggle: none

# Specify whether the Series disaggregation should be a toggle (like units).
series_toggle: true

# Control the behavior of breadcrumbs for certain types of content.
breadcrumbs:
  post:
    - label: general.home
      path: /
 #   - label: menu.updates
 #     path: /news
  goal:
    - label: general.home
      path: /
    - label: general.goals
      path: /goals
  indicator:
    - label: general.home
      path: /
    - label: general.goals
      path: /goals

# Metadata tabs test. 
metadata_tabs:
  - scope: national
    title: indicator.national_metadata
    description: indicator.national_metadata_blurb
 # - scope: global
 #   title: indicator.global_metadata
 #   description: indicator.global_metadata_blurb
  - scope: sources
    title: indicator.sources
    description: ''

# Goal color graph test
graph_color_set: 'accessible'

## To enhance the search functionality
search_index_extra_fields:
  - data_keywords

# Reporting status page
# reporting_status:
#    title: Reporting status on disaggregation
#    description: This page provides information on possible disaggregation for indicators and tracj the progress of included them in the hub
#    disaggregation_tabs: true

# bootstrap_5: true
# chartjs_3: true
progress_status:
    status_heading: status.progress_header
    status_types:
      - value: not_available
        label: status.progress_not_available
#        image: assets/img/progress/not-available.png
#        alt: status.progress_not_available
      - value: target_achieved
        label: status.progress_target_achieved
        image: assets/img/progress/target-achieved-gauge.png
        alt: status.progress_target_achieved
      - value: substantial_progress
        label: status.substantial_progress
        image: assets/img/progress/green-gauge.png
        alt: status.substantial_progress
      - value: moderate_progress
        label: status.moderate_progress
        image: assets/img/progress/yellow-gauge.png
        alt: status.moderate_progress
      - value: negligible_progress
        label: status.negligible_progress
        image: assets/img/progress/orange-gauge.png
        alt: status.negligible_progress
      - value: limited_progress
        label: status.limited_progress
        image: assets/img/progress/orange-gauge.png
        alt: status.limited_progress
      - value: deterioration
        label: status.deterioration
        image: assets/img/progress/red-gauge.png
        alt: status.deterioration
      - value: moderate_deterioration
        label: status.moderate_deterioration
        image: assets/img/progress/orange-gauge.png
        alt: status.moderate_deterioration
      - value: substantial_deterioration
        label: status.substantial_deterioration
        image: assets/img/progress/red-gauge.png
        alt: status.substantial_deterioration
